#!/bin/bash
#PBS -j oe
#PBS -m ae
#PBS -N update_all_biases 
#PBS -M momoe.yoshida@my.jcu.edu.au
#PBS -l walltime=00:10:00
#PBS -l select=1:ncpus=1:mem=16gb

set -euo pipefail

cd $PBS_O_WORKDIR
export SST_ENV=$PBS_O_WORKDIR

# Add this to all of your scripts
shopt -s expand_aliases
source /etc/profile.d/modules.sh

# Output some useful information about
# the job we are running
echo "Job identifier is $PBS_JOBID"
echo "Working directory is $PBS_O_WORKDIR"
echo "Start time: $(date)"

DAY_OF_YEAR_DECIMAL=$((10#$DAY_OF_YEAR))

# Load the container we want to use
# It is a good idea to always specify the version number 
module purge
module load matlab/2024a
#module load gcc/10.5.0

: "${DIRECTION:=1}"

matlab -batch "\
fprintf('MATLAB started\n'); \
fprintf('Before clear mex\n'); \
clear mex; \
fprintf('After clear mex\n'); \
fprintf('Calling update_all_biases(%d,%d,%d)\n', \
    ${YEAR},${DAY_OF_YEAR_DECIMAL},${DIRECTION}); \
drawnow; \
update_all_biases(${YEAR},${DAY_OF_YEAR_DECIMAL},${DIRECTION}); \
fprintf('update_all_biases returned normally\n'); \
drawnow;"

echo "End time: $(date)"
